---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/batexpert/public_html/lp/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/rm -f $DEPLOYPATH/landingpage.html
    - /bin/rm -f $DEPLOYPATH/landingpage-v2.html
    - /bin/rm -f $DEPLOYPATH/landingpage-v3.html
    - /bin/cp -f baterie-auto-la-domiciliu.html $DEPLOYPATH
    - /bin/cp -f baterie-auto-la-domiciliu-v2.html $DEPLOYPATH
    - /bin/cp -f baterie-auto-la-domiciliu-v3.html $DEPLOYPATH
    - /bin/cp -f baterie-auto-la-domiciliu-constanta.html $DEPLOYPATH
