---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/batexpert/public_html/lp/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -f landingpage.html $DEPLOYPATH
    - /bin/cp -f landingpage-v2.html $DEPLOYPATH
